name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort

      - name: Run isort
        run: isort --check-only nuclear_news_indexer.py

      - name: Run black
        run: black --check --line-length 79 nuclear_news_indexer.py

      - name: Run flake8
        run: flake8 nuclear_news_indexer.py

      - name: Run unit tests
        run: |
          if [ -d tests ]; then
            python -m unittest discover tests
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: rjglabs_ai-nuke-newsfeed
          SONAR_ORGANIZATION: rjglabs
