name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort

      - name: Run isort
        run: isort --check-only nuclear_news_indexer.py

      - name: Run black
        run: black --check --line-length 79 nuclear_news_indexer.py

      - name: Run flake8
        run: flake8 nuclear_news_indexer.py

      - name: Set dummy Key Vault URL for tests
        run: echo "KEY_VAULT_URL=https://dummy.vault.azure.net/" >> $GITHUB_ENV

      - name: Set dummy Azure secrets for tests
        run: |
          echo "AI-OPENAI-KEY=dummy-openai-key" >> $GITHUB_ENV
          echo "AI-OPENAI-ENDPOINT=https://dummy-openai-endpoint.openai.azure.com/" >> $GITHUB_ENV
          echo "AI-OPENAI-DEPLOYMENT=dummy-deployment" >> $GITHUB_ENV
          echo "AI-SEARCH-PRIMARY-KEY=dummy-search-key" >> $GITHUB_ENV
          echo "AI-SEARCH-ENDPOINT=https://dummy-search-endpoint.search.windows.net/" >> $GITHUB_ENV

      - name: Install coverage
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover tests
          coverage xml

      - name: Run Snyk to check for vulnerabilities (requirements.txt)
        uses: snyk/actions/python@master
        with:
          args: --file=requirements.txt --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities (requirements-dev.txt)
        uses: snyk/actions/python@master
        with:
          args: --file=requirements-dev.txt --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: rjglabs_ai-nuke-newsfeed
          SONAR_ORGANIZATION: rjglabs
